services:
  - type: web
    name: teltonika-tcp-server
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TCP_PORT
        value: "5000"
      - key: TCP_HOST
        value: "0.0.0.0"
      - key: WEB_APP_API_URL
        sync: false  # Set this to your web app URL
      - key: API_TIMEOUT
        value: "10000"
      - key: SERVER_ID
        value: "tcp-server-1"
      - key: LOG_LEVEL
        value: "info"
      - key: ENABLE_DEBUG_LOGGING
        value: "false"
      - key: MAX_CONNECTIONS
        value: "100"
      - key: CONNECTION_TIMEOUT
        value: "30000"
      - key: HEALTH_PORT
        value: "8080"
      - key: NODE_ENV
        value: "production"
    healthCheckPath: http://localhost:8080/
    autoDeploy: true
    # Note: Render.com web services don't support raw TCP connections
    # This will only work for the health check endpoint
