apiVersion: apps/v1
kind: Deployment
metadata:
  name: teltonika-tcp-server
  labels:
    app: teltonika-tcp-server
spec:
  replicas: 1  # TCP servers should typically be single instance
  selector:
    matchLabels:
      app: teltonika-tcp-server
  template:
    metadata:
      labels:
        app: teltonika-tcp-server
    spec:
      containers:
      - name: teltonika-tcp-server
        image: your-registry/teltonika-tcp-server:latest
        ports:
        - containerPort: 5000
          name: tcp
        - containerPort: 8080
          name: health
        env:
        - name: NODE_ENV
          value: "production"
        - name: TCP_PORT
          value: "5000"
        - name: TCP_HOST
          value: "0.0.0.0"
        - name: WEB_APP_API_URL
          value: "https://your-web-app.com/api/gps/teltonika"
        - name: API_TIMEOUT
          value: "10000"
        - name: SERVER_ID
          value: "tcp-server-k8s"
        - name: LOG_LEVEL
          value: "info"
        - name: ENABLE_DEBUG_LOGGING
          value: "false"
        - name: MAX_CONNECTIONS
          value: "100"
        - name: CONNECTION_TIMEOUT
          value: "30000"
        - name: HEALTH_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: teltonika-tcp-server-service
spec:
  selector:
    app: teltonika-tcp-server
  ports:
  - name: tcp
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teltonika-tcp-server-config
data:
  TCP_PORT: "5000"
  TCP_HOST: "0.0.0.0"
  API_TIMEOUT: "10000"
  LOG_LEVEL: "info"
  MAX_CONNECTIONS: "100"
  CONNECTION_TIMEOUT: "30000"
  HEALTH_PORT: "8080"
